/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class VentanaPreguntas11 extends javax.swing.JFrame {
public int valorPasado;
Cuestionario cuestionarioOnce;
Validacion validar;
    public VentanaPreguntas11() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }
    
    public VentanaPreguntas11(int valorPasado) {
        this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }
    
    public void cargarClases(int valorPasado){
        cuestionarioOnce = new Cuestionario(valorPasado);
        validar = new Validacion();
    
    }

    public void cargarRadioBotones() {
        cargarRadioPregunta19();
        cargarRadioPregunta20();
        cargarRadioPregunta21();

    }

    public void cargarRadioPregunta19() {
        ButtonGroup grupoPregunta19 = new ButtonGroup();
        grupoPregunta19.add(radioNuncaPregunta31);
        grupoPregunta19.add(radioVecesPregunta31);
        grupoPregunta19.add(radioSiemprePregunta31);

    }

    public void cargarRadioPregunta20() {
        ButtonGroup grupoPregunta20 = new ButtonGroup();
        grupoPregunta20.add(radioNuncaPregunta32);
        grupoPregunta20.add(radioVecesPregunta32);
        grupoPregunta20.add(radioSiemprePregunta32);

    }

    public void cargarRadioPregunta21() {
        ButtonGroup grupoPregunta21 = new ButtonGroup();
        grupoPregunta21.add(radioNuncaPregunta33);
        grupoPregunta21.add(radioVecesPregunta33);
        grupoPregunta21.add(radioSiemprePregunta33);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelPregunta11 = new javax.swing.JLabel();
        btnSiguiente11 = new javax.swing.JButton();
        panelPregunta33 = new javax.swing.JPanel();
        radioNuncaPregunta33 = new javax.swing.JRadioButton();
        radioVecesPregunta33 = new javax.swing.JRadioButton();
        radioSiemprePregunta33 = new javax.swing.JRadioButton();
        labelPregunta33 = new javax.swing.JLabel();
        panelPregunta32 = new javax.swing.JPanel();
        labelPregunta32 = new javax.swing.JLabel();
        radioNuncaPregunta32 = new javax.swing.JRadioButton();
        radioVecesPregunta32 = new javax.swing.JRadioButton();
        radioSiemprePregunta32 = new javax.swing.JRadioButton();
        panelPregunta31 = new javax.swing.JPanel();
        radioNuncaPregunta31 = new javax.swing.JRadioButton();
        radioVecesPregunta31 = new javax.swing.JRadioButton();
        radioSiemprePregunta31 = new javax.swing.JRadioButton();
        labelPregunta31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelPregunta11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPregunta11.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelPregunta11, gridBagConstraints);

        btnSiguiente11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente11.setText("Siguiente");
        btnSiguiente11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSiguiente11, gridBagConstraints);

        panelPregunta33.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta33.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioNuncaPregunta33.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta33.setText("Nunca");
        radioNuncaPregunta33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta33ActionPerformed(evt);
            }
        });
        panelPregunta33.add(radioNuncaPregunta33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta33.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta33.setText("Algunas veces");
        radioVecesPregunta33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta33ActionPerformed(evt);
            }
        });
        panelPregunta33.add(radioVecesPregunta33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta33.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta33.setText("Siempre");
        radioSiemprePregunta33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta33ActionPerformed(evt);
            }
        });
        panelPregunta33.add(radioSiemprePregunta33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelPregunta33.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta33.setText("33. Formo parte algún grupo o equipo de deporte o de ocio para compartir intereses o aficiones.");
        panelPregunta33.add(labelPregunta33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta33, gridBagConstraints);

        panelPregunta32.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta32.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta32.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta32.setText("32. Si he de estar solo no me agobio por eso.");
        panelPregunta32.add(labelPregunta32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta32.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta32.setText("Nunca");
        radioNuncaPregunta32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta32ActionPerformed(evt);
            }
        });
        panelPregunta32.add(radioNuncaPregunta32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta32.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta32.setText("Algunas veces");
        radioVecesPregunta32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta32ActionPerformed(evt);
            }
        });
        panelPregunta32.add(radioVecesPregunta32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta32.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta32.setText("Siempre");
        radioSiemprePregunta32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta32ActionPerformed(evt);
            }
        });
        panelPregunta32.add(radioSiemprePregunta32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta32, gridBagConstraints);

        panelPregunta31.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta31.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioNuncaPregunta31.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta31.setText("Nunca");
        radioNuncaPregunta31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta31ActionPerformed(evt);
            }
        });
        panelPregunta31.add(radioNuncaPregunta31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta31.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta31.setText("Algunas veces");
        radioVecesPregunta31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta31ActionPerformed(evt);
            }
        });
        panelPregunta31.add(radioVecesPregunta31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta31.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta31.setText("Siempre");
        radioSiemprePregunta31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta31ActionPerformed(evt);
            }
        });
        panelPregunta31.add(radioSiemprePregunta31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelPregunta31.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta31.setText("31. Controlo bien mis miedos y temores.");
        panelPregunta31.add(labelPregunta31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta31, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente11ActionPerformed
          if(!validar.preguntaUno || !validar.preguntaDos || !validar.preguntaTres ){
             JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");
        
        
        }
        else {
         cuestionarioOnce.retornarSubtotal();
        cuestionarioOnce.retornarTotal();
        
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioOnce.retornarSubtotal() );
//        JOptionPane.showMessageDialog(null, "El total es "+cuestionarioOnce.retornarTotal() );
         VentanaPreguntas12 ventanaDoce = new VentanaPreguntas12(cuestionarioOnce.retornarTotal());
        ventanaDoce.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnSiguiente11ActionPerformed

    private void radioNuncaPregunta31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta31ActionPerformed
        if(radioNuncaPregunta31.isSelected() == true){
            cuestionarioOnce.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
           // JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioOnce.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioNuncaPregunta31ActionPerformed

    private void radioVecesPregunta31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta31ActionPerformed
        if(radioVecesPregunta31.isSelected() == true){
            cuestionarioOnce.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioOnce.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioVecesPregunta31ActionPerformed

    private void radioSiemprePregunta31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta31ActionPerformed
        if(radioSiemprePregunta31.isSelected() == true){
            cuestionarioOnce.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
           // JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioOnce.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioSiemprePregunta31ActionPerformed

    private void radioNuncaPregunta32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta32ActionPerformed
       if(radioNuncaPregunta32.isSelected() == true){
           cuestionarioOnce.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
           validar.preguntaDos = true;
          // JOptionPane.showMessageDialog(null, "El valor de la pregunta dos "+ cuestionarioOnce.getValorPreguntaDos());
       
       }
    }//GEN-LAST:event_radioNuncaPregunta32ActionPerformed

    private void radioVecesPregunta32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta32ActionPerformed
          if(radioVecesPregunta32.isSelected() == true){
           cuestionarioOnce.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
           validar.preguntaDos = true;
         //  JOptionPane.showMessageDialog(null, "El valor de la pregunta dos "+ cuestionarioOnce.getValorPreguntaDos());
       
       }
    }//GEN-LAST:event_radioVecesPregunta32ActionPerformed

    private void radioSiemprePregunta32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta32ActionPerformed
             if(radioSiemprePregunta32.isSelected() == true){
           cuestionarioOnce.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
           validar.preguntaDos = true;
          // JOptionPane.showMessageDialog(null, "El valor de la pregunta dos "+ cuestionarioOnce.getValorPreguntaDos());
       
       }
    }//GEN-LAST:event_radioSiemprePregunta32ActionPerformed

    private void radioNuncaPregunta33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta33ActionPerformed
        if(radioNuncaPregunta33.isSelected() == true){
            cuestionarioOnce.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es "+ cuestionarioOnce.getValorPreguntaTres());
        
        
        }
    }//GEN-LAST:event_radioNuncaPregunta33ActionPerformed

    private void radioVecesPregunta33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta33ActionPerformed
         if(radioVecesPregunta33.isSelected() == true){
            cuestionarioOnce.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaTres = true;
          //  JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es "+ cuestionarioOnce.getValorPreguntaTres());
        
        
        }
    }//GEN-LAST:event_radioVecesPregunta33ActionPerformed

    private void radioSiemprePregunta33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta33ActionPerformed
          if(radioSiemprePregunta33.isSelected() == true){
            cuestionarioOnce.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
            validar.preguntaTres = true;
           // JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es "+ cuestionarioOnce.getValorPreguntaTres());
        
        
        }
    }//GEN-LAST:event_radioSiemprePregunta33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta11;
    private javax.swing.JLabel labelPregunta31;
    private javax.swing.JLabel labelPregunta32;
    private javax.swing.JLabel labelPregunta33;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta31;
    private javax.swing.JPanel panelPregunta32;
    private javax.swing.JPanel panelPregunta33;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta31;
    private javax.swing.JRadioButton radioNuncaPregunta32;
    private javax.swing.JRadioButton radioNuncaPregunta33;
    private javax.swing.JRadioButton radioSiemprePregunta31;
    private javax.swing.JRadioButton radioSiemprePregunta32;
    private javax.swing.JRadioButton radioSiemprePregunta33;
    private javax.swing.JRadioButton radioVecesPregunta31;
    private javax.swing.JRadioButton radioVecesPregunta32;
    private javax.swing.JRadioButton radioVecesPregunta33;
    // End of variables declaration//GEN-END:variables
}
