/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas1 extends javax.swing.JFrame  {

    public int totalUno = 0;
    Validacion validar;
    Cuestionario cuestionarioUno = new Cuestionario(totalUno);
   

    public VentanaPreguntas1() {
       
        initComponents();
        setLocationRelativeTo(this);
     
        
        cargarRadioBotones();
        cargarClases();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }

    

    

    public void cargarRadioBotones() {
        cargarRadioPreguntaUno();
        cargarRadioPreguntaDos();
        cargarRadioPreguntaTres();

    }

    public void cargarClases() {
        validar = new Validacion();
    }

    public void cargarRadioPreguntaUno() {
        ButtonGroup grupoPreguntaUno = new ButtonGroup();
        grupoPreguntaUno.add(radioNuncaPregunta1);
        grupoPreguntaUno.add(radioVecesPregunta1);
        grupoPreguntaUno.add(radioSiemprePregunta1);

    }

    public void cargarRadioPreguntaDos() {
        ButtonGroup grupoPreguntaDos = new ButtonGroup();
        grupoPreguntaDos.add(radioNuncaPregunta2);
        grupoPreguntaDos.add(radioVecesPregunta2);
        grupoPreguntaDos.add(radioSiemprePregunta2);

    }

    public void cargarRadioPreguntaTres() {
        ButtonGroup grupoPreguntaTres = new ButtonGroup();
        grupoPreguntaTres.add(radioNuncaPregunta3);
        grupoPreguntaTres.add(radioVecesPregunta3);
        grupoPreguntaTres.add(radioSiemprePregunta3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelTItuloVentana1 = new javax.swing.JLabel();
        btnPregunta1 = new javax.swing.JButton();
        panelPregunta3 = new javax.swing.JPanel();
        labelPregunta3 = new javax.swing.JLabel();
        radioNuncaPregunta3 = new javax.swing.JRadioButton();
        radioVecesPregunta3 = new javax.swing.JRadioButton();
        radioSiemprePregunta3 = new javax.swing.JRadioButton();
        panelPregunta2 = new javax.swing.JPanel();
        labelPregunta2 = new javax.swing.JLabel();
        radioNuncaPregunta2 = new javax.swing.JRadioButton();
        radioVecesPregunta2 = new javax.swing.JRadioButton();
        radioSiemprePregunta2 = new javax.swing.JRadioButton();
        panelPregunta1 = new javax.swing.JPanel();
        labelPreguntaUno = new javax.swing.JLabel();
        radioNuncaPregunta1 = new javax.swing.JRadioButton();
        radioVecesPregunta1 = new javax.swing.JRadioButton();
        radioSiemprePregunta1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelTItuloVentana1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTItuloVentana1.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelTItuloVentana1, gridBagConstraints);

        btnPregunta1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPregunta1.setText("Siguiente");
        btnPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregunta1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnPregunta1, gridBagConstraints);

        panelPregunta3.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta3.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta3.setText("3. Cuando las cosas me van mal, mi estado de ánimo aguanta hasta que las cosas vayan mejor");
        panelPregunta3.add(labelPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta3.setText("Nunca");
        radioNuncaPregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta3ActionPerformed(evt);
            }
        });
        panelPregunta3.add(radioNuncaPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta3.setText("Algunas veces");
        radioVecesPregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta3ActionPerformed(evt);
            }
        });
        panelPregunta3.add(radioVecesPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta3.setText("Siempre");
        radioSiemprePregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta3ActionPerformed(evt);
            }
        });
        panelPregunta3.add(radioSiemprePregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta3, gridBagConstraints);

        panelPregunta2.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta2.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta2.setText("2. Soy capaz de auto motivarme para aprender, estudiar, aprobar, conseguir algo");
        panelPregunta2.add(labelPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta2.setText("Nunca");
        radioNuncaPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta2ActionPerformed(evt);
            }
        });
        panelPregunta2.add(radioNuncaPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta2.setText("Algunas veces");
        radioVecesPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta2ActionPerformed(evt);
            }
        });
        panelPregunta2.add(radioVecesPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta2.setText("Siempre");
        radioSiemprePregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta2ActionPerformed(evt);
            }
        });
        panelPregunta2.add(radioSiemprePregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta2, gridBagConstraints);

        panelPregunta1.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta1.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPreguntaUno.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPreguntaUno.setText("1. Me conozco a mí mismo, sé lo que pienso, lo que siento y lo que hago.");
        panelPregunta1.add(labelPreguntaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta1.setText("Nunca");
        radioNuncaPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta1ActionPerformed(evt);
            }
        });
        panelPregunta1.add(radioNuncaPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta1.setText("Algunas veces");
        radioVecesPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta1ActionPerformed(evt);
            }
        });
        panelPregunta1.add(radioVecesPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta1.setText("Siempre");
        radioSiemprePregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta1ActionPerformed(evt);
            }
        });
        panelPregunta1.add(radioSiemprePregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregunta1ActionPerformed
        if (validar.preguntaUno == false || validar.preguntaDos == false || validar.preguntaTres == false) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");

        } else {
            cuestionarioUno.retornarSubtotal();
            cuestionarioUno.retornarTotal();

//            JOptionPane.showMessageDialog(null, "El subtotal es " + cuestionarioUno.retornarSubtotal());
//            JOptionPane.showMessageDialog(null, "El total " + cuestionarioUno.retornarTotal());
            
            VentanaPreguntas2 ventanaDos = new VentanaPreguntas2(cuestionarioUno.retornarTotal());
            ventanaDos.setVisible(true);
            this.dispose();

        }


    }//GEN-LAST:event_btnPregunta1ActionPerformed

    private void radioNuncaPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta1ActionPerformed
        if (radioNuncaPregunta1.isSelected() == true) {
            cuestionarioUno.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaUno());
    }//GEN-LAST:event_radioNuncaPregunta1ActionPerformed

    private void radioVecesPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta1ActionPerformed
        if (radioVecesPregunta1.isSelected() == true) {
            cuestionarioUno.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
        }
        // JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaUno());
    }//GEN-LAST:event_radioVecesPregunta1ActionPerformed

    private void radioSiemprePregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta1ActionPerformed
        if (radioSiemprePregunta1.isSelected() == true) {
            cuestionarioUno.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaUno());
    }//GEN-LAST:event_radioSiemprePregunta1ActionPerformed

    private void radioNuncaPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta2ActionPerformed
        if (radioNuncaPregunta2.isSelected() == true) {
            cuestionarioUno.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaDos());
    }//GEN-LAST:event_radioNuncaPregunta2ActionPerformed

    private void radioVecesPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta2ActionPerformed
        if (radioVecesPregunta2.isSelected() == true) {
            cuestionarioUno.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaDos());
    }//GEN-LAST:event_radioVecesPregunta2ActionPerformed

    private void radioSiemprePregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta2ActionPerformed
        if (radioSiemprePregunta2.isSelected() == true) {
            cuestionarioUno.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaDos());
    }//GEN-LAST:event_radioSiemprePregunta2ActionPerformed

    private void radioNuncaPregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta3ActionPerformed
        if (radioNuncaPregunta3.isSelected() == true) {
            cuestionarioUno.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
            validar.preguntaTres = true;
        }
        // JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaTres());
    }//GEN-LAST:event_radioNuncaPregunta3ActionPerformed

    private void radioVecesPregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta3ActionPerformed
        if (radioVecesPregunta3.isSelected() == true) {
            cuestionarioUno.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaTres = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaTres());
    }//GEN-LAST:event_radioVecesPregunta3ActionPerformed

    private void radioSiemprePregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta3ActionPerformed
        if (radioSiemprePregunta3.isSelected() == true) {
            cuestionarioUno.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
            validar.preguntaTres = true;
        }
        //&JOptionPane.showMessageDialog(null, cuestionarioUno.getValorPreguntaTres());
    }//GEN-LAST:event_radioSiemprePregunta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPregunta1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta2;
    private javax.swing.JLabel labelPregunta3;
    private javax.swing.JLabel labelPreguntaUno;
    private javax.swing.JLabel labelTItuloVentana1;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta1;
    private javax.swing.JPanel panelPregunta2;
    private javax.swing.JPanel panelPregunta3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta1;
    private javax.swing.JRadioButton radioNuncaPregunta2;
    private javax.swing.JRadioButton radioNuncaPregunta3;
    private javax.swing.JRadioButton radioSiemprePregunta1;
    private javax.swing.JRadioButton radioSiemprePregunta2;
    private javax.swing.JRadioButton radioSiemprePregunta3;
    private javax.swing.JRadioButton radioVecesPregunta1;
    private javax.swing.JRadioButton radioVecesPregunta2;
    private javax.swing.JRadioButton radioVecesPregunta3;
    // End of variables declaration//GEN-END:variables

   
}
