/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas4 extends javax.swing.JFrame {
    public int valorPasado;
    Cuestionario cuestionarioCuatro;
    Validacion validar;

    public VentanaPreguntas4() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }
     public VentanaPreguntas4(int valorPasado) {
         this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }
     
     public void cargarClases(int valorPasado){
     cuestionarioCuatro = new Cuestionario(valorPasado);
     validar = new Validacion();
     
     }

    public void cargarRadioBotones() {
        cargarRadioPreguntaDiez();
        cargarRadioPreguntaOnce();
        cargarRadioPreguntaDoce();

    }

    public void cargarRadioPreguntaDiez() {
        ButtonGroup grupoPreguntaDiez = new ButtonGroup();
        grupoPreguntaDiez.add(radioNuncaPregunta10);
        grupoPreguntaDiez.add(radioVecesPregunta10);
        grupoPreguntaDiez.add(radioSiemprePregunta10);

    }
    public void cargarRadioPreguntaOnce() {
        ButtonGroup grupoPreguntaOnce = new ButtonGroup();
        grupoPreguntaOnce.add(radioNuncaPregunta11);
        grupoPreguntaOnce.add(radioVecesPregunta11);
        grupoPreguntaOnce.add(radioSiemprePregunta11);

    }
    public void cargarRadioPreguntaDoce() {
        ButtonGroup grupoPreguntaDoce = new ButtonGroup();
        grupoPreguntaDoce.add(radioNuncaPregunta12);
        grupoPreguntaDoce.add(radioVecesPregunta12);
        grupoPreguntaDoce.add(radioSiemprePregunta12);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelTItulo4 = new javax.swing.JLabel();
        btnSiguieinte4 = new javax.swing.JButton();
        panelPregunta12 = new javax.swing.JPanel();
        labelPregunta12 = new javax.swing.JLabel();
        radioNuncaPregunta12 = new javax.swing.JRadioButton();
        radioVecesPregunta12 = new javax.swing.JRadioButton();
        radioSiemprePregunta12 = new javax.swing.JRadioButton();
        panelPregunta11 = new javax.swing.JPanel();
        labelPregunta11 = new javax.swing.JLabel();
        radioNuncaPregunta11 = new javax.swing.JRadioButton();
        radioVecesPregunta11 = new javax.swing.JRadioButton();
        radioSiemprePregunta11 = new javax.swing.JRadioButton();
        panelPregunta10 = new javax.swing.JPanel();
        labelPregunta10 = new javax.swing.JLabel();
        radioNuncaPregunta10 = new javax.swing.JRadioButton();
        radioVecesPregunta10 = new javax.swing.JRadioButton();
        radioSiemprePregunta10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelTItulo4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTItulo4.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelTItulo4, gridBagConstraints);

        btnSiguieinte4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguieinte4.setText("Siguiente");
        btnSiguieinte4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguieinte4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSiguieinte4, gridBagConstraints);

        panelPregunta12.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta12.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta12.setText("12. Cuando me piden que diga o haga algo que me parece inaceptable me niego a hacerlo. ");
        panelPregunta12.add(labelPregunta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta12.setText("Nunca");
        radioNuncaPregunta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta12ActionPerformed(evt);
            }
        });
        panelPregunta12.add(radioNuncaPregunta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta12.setText("Algunas veces");
        radioVecesPregunta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta12ActionPerformed(evt);
            }
        });
        panelPregunta12.add(radioVecesPregunta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta12.setText("Siempre");
        radioSiemprePregunta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta12ActionPerformed(evt);
            }
        });
        panelPregunta12.add(radioSiemprePregunta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta12, gridBagConstraints);

        panelPregunta11.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta11.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta11.setText("11. Hablo conmigo mismo, en voz baja claro.");
        panelPregunta11.add(labelPregunta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta11.setText("Nunca");
        radioNuncaPregunta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta11ActionPerformed(evt);
            }
        });
        panelPregunta11.add(radioNuncaPregunta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta11.setText("Algunas veces");
        radioVecesPregunta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta11ActionPerformed(evt);
            }
        });
        panelPregunta11.add(radioVecesPregunta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta11.setText("Siempre");
        radioSiemprePregunta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta11ActionPerformed(evt);
            }
        });
        panelPregunta11.add(radioSiemprePregunta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta11, gridBagConstraints);

        panelPregunta10.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta10.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta10.setText("10. Controlo mis pensamientos, pienso lo que de verdad me interesa. ");
        panelPregunta10.add(labelPregunta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta10.setText("Nunca");
        radioNuncaPregunta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta10ActionPerformed(evt);
            }
        });
        panelPregunta10.add(radioNuncaPregunta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta10.setText("Algunas veces");
        radioVecesPregunta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta10ActionPerformed(evt);
            }
        });
        panelPregunta10.add(radioVecesPregunta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta10.setText("Siempre");
        radioSiemprePregunta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta10ActionPerformed(evt);
            }
        });
        panelPregunta10.add(radioSiemprePregunta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguieinte4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguieinte4ActionPerformed
         if (validar.preguntaUno == false || validar.preguntaDos == false || validar.preguntaTres == false) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");

        } else {
//            JOptionPane.showMessageDialog(null, "El valor pasado es " + valorPasado);

            cuestionarioCuatro.retornarSubtotal();
            cuestionarioCuatro.retornarTotal();
            cuestionarioCuatro.getTotal();
//            JOptionPane.showMessageDialog(null, "El total es " + cuestionarioCuatro.getTotal());
//
//            JOptionPane.showMessageDialog(null, "El subtotal es " + cuestionarioCuatro.retornarSubtotal());
//            JOptionPane.showMessageDialog(null, "El total " + cuestionarioCuatro.retornarTotal());
            VentanaPreguntas5 ventanaCinco = new VentanaPreguntas5(cuestionarioCuatro.retornarTotal());
            ventanaCinco.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btnSiguieinte4ActionPerformed

    private void radioNuncaPregunta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta10ActionPerformed
        if (radioNuncaPregunta10.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
        }
       // JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaUno());
    }//GEN-LAST:event_radioNuncaPregunta10ActionPerformed

    private void radioVecesPregunta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta10ActionPerformed
        if (radioVecesPregunta10.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaUno());
    }//GEN-LAST:event_radioVecesPregunta10ActionPerformed

    private void radioSiemprePregunta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta10ActionPerformed
        if (radioSiemprePregunta10.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
        }
       // JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaUno());
    }//GEN-LAST:event_radioSiemprePregunta10ActionPerformed

    private void radioNuncaPregunta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta11ActionPerformed
        if (radioNuncaPregunta11.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaDos());
    }//GEN-LAST:event_radioNuncaPregunta11ActionPerformed

    private void radioVecesPregunta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta11ActionPerformed
         if (radioVecesPregunta11.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
        }
       // JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaDos());
        
    }//GEN-LAST:event_radioVecesPregunta11ActionPerformed

    private void radioSiemprePregunta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta11ActionPerformed
        if (radioSiemprePregunta11.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaTres());
    }//GEN-LAST:event_radioSiemprePregunta11ActionPerformed

    private void radioNuncaPregunta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta12ActionPerformed
        if (radioNuncaPregunta12.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
            validar.preguntaTres = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaTres());
    }//GEN-LAST:event_radioNuncaPregunta12ActionPerformed

    private void radioVecesPregunta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta12ActionPerformed
           if (radioVecesPregunta12.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaTres = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaTres());
        
    }//GEN-LAST:event_radioVecesPregunta12ActionPerformed

    private void radioSiemprePregunta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta12ActionPerformed
         if (radioSiemprePregunta12.isSelected() == true) {
            cuestionarioCuatro.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
            validar.preguntaTres = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioCuatro.getValorPreguntaTres());
    }//GEN-LAST:event_radioSiemprePregunta12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguieinte4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta10;
    private javax.swing.JLabel labelPregunta11;
    private javax.swing.JLabel labelPregunta12;
    private javax.swing.JLabel labelTItulo4;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta10;
    private javax.swing.JPanel panelPregunta11;
    private javax.swing.JPanel panelPregunta12;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta10;
    private javax.swing.JRadioButton radioNuncaPregunta11;
    private javax.swing.JRadioButton radioNuncaPregunta12;
    private javax.swing.JRadioButton radioSiemprePregunta10;
    private javax.swing.JRadioButton radioSiemprePregunta11;
    private javax.swing.JRadioButton radioSiemprePregunta12;
    private javax.swing.JRadioButton radioVecesPregunta10;
    private javax.swing.JRadioButton radioVecesPregunta11;
    private javax.swing.JRadioButton radioVecesPregunta12;
    // End of variables declaration//GEN-END:variables
}
