/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas2 extends javax.swing.JFrame {

    public int valorPasado;
    Cuestionario cuestionarioDos;
    Validacion validar;
    

    /**
     * Creates new form Ventana
     */
    public VentanaPreguntas2() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }

    public VentanaPreguntas2(int valorPasado) {
       
      
        this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
       
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }

    public void cargarClases(int valorPasado) {
        cuestionarioDos = new Cuestionario(valorPasado);
        validar = new Validacion();

    }

   

    public void cargarRadioBotones() {
        cargarRadioPreguntaCuatro();
        cargarRadioPreguntaCinco();
        cargarRadioPreguntaSeis();

    }

    public void cargarRadioPreguntaCuatro() {
        ButtonGroup grupoPreguntaCuatro = new ButtonGroup();
        grupoPreguntaCuatro.add(radioNuncaPregunta4);
        grupoPreguntaCuatro.add(radioVecesPregunta4);
        grupoPreguntaCuatro.add(radioSiemprePregunta4);

    }

    public void cargarRadioPreguntaCinco() {
        ButtonGroup grupoPreguntaCinco = new ButtonGroup();
        grupoPreguntaCinco.add(radioNuncaPregunta5);
        grupoPreguntaCinco.add(radioVecesPregunta5);
        grupoPreguntaCinco.add(radioSiemprePregunta5);

    }

    public void cargarRadioPreguntaSeis() {
        ButtonGroup grupoPreguntaSeis = new ButtonGroup();
        grupoPreguntaSeis.add(radioNuncaPregunta6);
        grupoPreguntaSeis.add(radioVecesPregunta6);
        grupoPreguntaSeis.add(radioSiemprePregunta6);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelTitulo2 = new javax.swing.JLabel();
        btnSiguiente2 = new javax.swing.JButton();
        panelPregunta6 = new javax.swing.JPanel();
        labelPregunta6 = new javax.swing.JLabel();
        radioNuncaPregunta6 = new javax.swing.JRadioButton();
        radioVecesPregunta6 = new javax.swing.JRadioButton();
        radioSiemprePregunta6 = new javax.swing.JRadioButton();
        panelPregunta5 = new javax.swing.JPanel();
        labelPregunta5 = new javax.swing.JLabel();
        radioNuncaPregunta5 = new javax.swing.JRadioButton();
        radioVecesPregunta5 = new javax.swing.JRadioButton();
        radioSiemprePregunta5 = new javax.swing.JRadioButton();
        panelPregunta4 = new javax.swing.JPanel();
        labelPregunta4 = new javax.swing.JLabel();
        radioNuncaPregunta4 = new javax.swing.JRadioButton();
        radioVecesPregunta4 = new javax.swing.JRadioButton();
        radioSiemprePregunta4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTitulo2.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelTitulo2, gridBagConstraints);

        btnSiguiente2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente2.setText("Siguiente");
        btnSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSiguiente2, gridBagConstraints);

        panelPregunta6.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta6.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta6.setText("6. Sé lo que es más importante en cada momento.");
        panelPregunta6.add(labelPregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta6.setText("Nunca");
        radioNuncaPregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta6ActionPerformed(evt);
            }
        });
        panelPregunta6.add(radioNuncaPregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta6.setText("Algunas veces");
        radioVecesPregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta6ActionPerformed(evt);
            }
        });
        panelPregunta6.add(radioVecesPregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta6.setText("Siempre");
        radioSiemprePregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta6ActionPerformed(evt);
            }
        });
        panelPregunta6.add(radioSiemprePregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta6, gridBagConstraints);

        panelPregunta5.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta5.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta5.setText("5. Sé qué cosas me ponen alegre y qué cosas me ponen triste. ");
        panelPregunta5.add(labelPregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta5.setText("Nunca");
        radioNuncaPregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta5ActionPerformed(evt);
            }
        });
        panelPregunta5.add(radioNuncaPregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta5.setText("Algunas veces");
        radioVecesPregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta5ActionPerformed(evt);
            }
        });
        panelPregunta5.add(radioVecesPregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta5.setText("Siempre");
        radioSiemprePregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta5ActionPerformed(evt);
            }
        });
        panelPregunta5.add(radioSiemprePregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta5, gridBagConstraints);

        panelPregunta4.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta4.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta4.setText("4. Llego a acuerdos razonables con otras personas cuando tenemos posturas enfrentadas. ");
        panelPregunta4.add(labelPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta4.setText("Nunca");
        radioNuncaPregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta4ActionPerformed(evt);
            }
        });
        panelPregunta4.add(radioNuncaPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta4.setText("Algunas veces");
        radioVecesPregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta4ActionPerformed(evt);
            }
        });
        panelPregunta4.add(radioVecesPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta4.setText("Siempre");
        radioSiemprePregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta4ActionPerformed(evt);
            }
        });
        panelPregunta4.add(radioSiemprePregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente2ActionPerformed
        if (validar.preguntaUno == false || validar.preguntaDos == false || validar.preguntaTres == false) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");

        } else {
            //JOptionPane.showMessageDialog(null, "El valor pasado es " + valorPasado);

            cuestionarioDos.retornarSubtotal();
            cuestionarioDos.retornarTotal();
            cuestionarioDos.getTotal();
//            JOptionPane.showMessageDialog(null, "El total es " + cuestionarioDos.getTotal());
//
//            JOptionPane.showMessageDialog(null, "El subtotal es " + cuestionarioDos.retornarSubtotal());
//            JOptionPane.showMessageDialog(null, "El total " + cuestionarioDos.retornarTotal());
           
            VentanaPreguntas3 ventanaTres = new VentanaPreguntas3(cuestionarioDos.retornarTotal());
            ventanaTres.setVisible(true);
            this.dispose();

        }


    }//GEN-LAST:event_btnSiguiente2ActionPerformed

    private void radioNuncaPregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta4ActionPerformed
        if (radioNuncaPregunta4.isSelected() == true) {
            cuestionarioDos.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaUno());
    }//GEN-LAST:event_radioNuncaPregunta4ActionPerformed

    private void radioVecesPregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta4ActionPerformed
        if (radioVecesPregunta4.isSelected() == true) {
            cuestionarioDos.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaUno());
    }//GEN-LAST:event_radioVecesPregunta4ActionPerformed

    private void radioSiemprePregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta4ActionPerformed
        if (radioSiemprePregunta4.isSelected() == true) {
            cuestionarioDos.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaUno());
    }//GEN-LAST:event_radioSiemprePregunta4ActionPerformed

    private void radioNuncaPregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta5ActionPerformed
        if (radioNuncaPregunta5.isSelected() == true) {
            cuestionarioDos.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaDos());
    }//GEN-LAST:event_radioNuncaPregunta5ActionPerformed

    private void radioVecesPregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta5ActionPerformed
        if (radioVecesPregunta5.isSelected() == true) {
            cuestionarioDos.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaDos());
    }//GEN-LAST:event_radioVecesPregunta5ActionPerformed

    private void radioSiemprePregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta5ActionPerformed
        if (radioSiemprePregunta5.isSelected() == true) {
            cuestionarioDos.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
        }
        // JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaDos());
    }//GEN-LAST:event_radioSiemprePregunta5ActionPerformed

    private void radioNuncaPregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta6ActionPerformed
        if (radioNuncaPregunta6.isSelected() == true) {
            cuestionarioDos.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
            validar.preguntaTres = true;
        }
        // JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaTres());
    }//GEN-LAST:event_radioNuncaPregunta6ActionPerformed

    private void radioVecesPregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta6ActionPerformed
        if (radioVecesPregunta6.isSelected() == true) {
            cuestionarioDos.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaTres = true;
        }
        //JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaTres());
    }//GEN-LAST:event_radioVecesPregunta6ActionPerformed

    private void radioSiemprePregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta6ActionPerformed
        if (radioSiemprePregunta6.isSelected() == true) {
            cuestionarioDos.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
            validar.preguntaTres = true;
        }
        // JOptionPane.showMessageDialog(null, cuestionarioDos.getValorPreguntaTres());
    }//GEN-LAST:event_radioSiemprePregunta6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta4;
    private javax.swing.JLabel labelPregunta5;
    private javax.swing.JLabel labelPregunta6;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta4;
    private javax.swing.JPanel panelPregunta5;
    private javax.swing.JPanel panelPregunta6;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta4;
    private javax.swing.JRadioButton radioNuncaPregunta5;
    private javax.swing.JRadioButton radioNuncaPregunta6;
    private javax.swing.JRadioButton radioSiemprePregunta4;
    private javax.swing.JRadioButton radioSiemprePregunta5;
    private javax.swing.JRadioButton radioSiemprePregunta6;
    private javax.swing.JRadioButton radioVecesPregunta4;
    private javax.swing.JRadioButton radioVecesPregunta5;
    private javax.swing.JRadioButton radioVecesPregunta6;
    // End of variables declaration//GEN-END:variables

 
}
