/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas9 extends javax.swing.JFrame {
public int valorPasado;
Cuestionario cuestionarioNueve;
Validacion validar;
    
    public VentanaPreguntas9() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }
    
     public VentanaPreguntas9(int valorPasado) {
         this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }
    
    public void cargarClases(int valorPasado){
        cuestionarioNueve = new Cuestionario(valorPasado);
        validar = new Validacion();
    
    }

    public void cargarRadioBotones() {
        cargarRadioPregunta19();
        cargarRadioPregunta20();
        cargarRadioPregunta21();

    }

    public void cargarRadioPregunta19() {
        ButtonGroup grupoPregunta19 = new ButtonGroup();
        grupoPregunta19.add(radioNuncaPregunta25);
        grupoPregunta19.add(radioVecesPregunta25);
        grupoPregunta19.add(radioSiemprePregunta25);

    }

    public void cargarRadioPregunta20() {
        ButtonGroup grupoPregunta20 = new ButtonGroup();
        grupoPregunta20.add(radioNuncaPregunta26);
        grupoPregunta20.add(radioVecesPregunta26);
        grupoPregunta20.add(radioSiemprePregunta26);

    }

    public void cargarRadioPregunta21() {
        ButtonGroup grupoPregunta21 = new ButtonGroup();
        grupoPregunta21.add(radioNuncaPregunta27);
        grupoPregunta21.add(radioVecesPregunta27);
        grupoPregunta21.add(radioSiemprePregunta27);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelPregunta9 = new javax.swing.JLabel();
        btnSiguiente9 = new javax.swing.JButton();
        panelPregunta27 = new javax.swing.JPanel();
        labelDosPregunta27 = new javax.swing.JLabel();
        radioNuncaPregunta27 = new javax.swing.JRadioButton();
        radioVecesPregunta27 = new javax.swing.JRadioButton();
        radioSiemprePregunta27 = new javax.swing.JRadioButton();
        labelPregunta27 = new javax.swing.JLabel();
        panelPregunta26 = new javax.swing.JPanel();
        labelPregunta26 = new javax.swing.JLabel();
        radioNuncaPregunta26 = new javax.swing.JRadioButton();
        radioVecesPregunta26 = new javax.swing.JRadioButton();
        radioSiemprePregunta26 = new javax.swing.JRadioButton();
        panelPregunta25 = new javax.swing.JPanel();
        labelPregunta25 = new javax.swing.JLabel();
        radioNuncaPregunta25 = new javax.swing.JRadioButton();
        radioVecesPregunta25 = new javax.swing.JRadioButton();
        radioSiemprePregunta25 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelPregunta9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPregunta9.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelPregunta9, gridBagConstraints);

        btnSiguiente9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente9.setText("Siguiente");
        btnSiguiente9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSiguiente9, gridBagConstraints);

        panelPregunta27.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta27.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDosPregunta27.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelDosPregunta27.setText("     para no perder el control y actuar apresuradamente. ");
        panelPregunta27.add(labelDosPregunta27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 600, -1));

        radioNuncaPregunta27.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta27.setText("Nunca");
        radioNuncaPregunta27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta27ActionPerformed(evt);
            }
        });
        panelPregunta27.add(radioNuncaPregunta27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta27.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta27.setText("Algunas veces");
        radioVecesPregunta27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta27ActionPerformed(evt);
            }
        });
        panelPregunta27.add(radioVecesPregunta27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta27.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta27.setText("Siempre");
        radioSiemprePregunta27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta27ActionPerformed(evt);
            }
        });
        panelPregunta27.add(radioSiemprePregunta27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelPregunta27.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta27.setText("27. En momentos de tensión y ansiedad soy capaz de relajarme y tranquilizarme");
        panelPregunta27.add(labelPregunta27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta27, gridBagConstraints);

        panelPregunta26.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta26.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta26.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta26.setText("26. Aprendo de los errores que cometo.");
        panelPregunta26.add(labelPregunta26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta26.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta26.setText("Nunca");
        radioNuncaPregunta26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta26ActionPerformed(evt);
            }
        });
        panelPregunta26.add(radioNuncaPregunta26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta26.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta26.setText("Algunas veces");
        radioVecesPregunta26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta26ActionPerformed(evt);
            }
        });
        panelPregunta26.add(radioVecesPregunta26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta26.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta26.setText("Siempre");
        radioSiemprePregunta26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta26ActionPerformed(evt);
            }
        });
        panelPregunta26.add(radioSiemprePregunta26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta26, gridBagConstraints);

        panelPregunta25.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta25.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta25.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta25.setText("25. Tengo buen sentido del humor.");
        panelPregunta25.add(labelPregunta25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta25.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta25.setText("Nunca");
        radioNuncaPregunta25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta25ActionPerformed(evt);
            }
        });
        panelPregunta25.add(radioNuncaPregunta25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta25.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta25.setText("Algunas veces");
        radioVecesPregunta25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta25ActionPerformed(evt);
            }
        });
        panelPregunta25.add(radioVecesPregunta25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta25.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta25.setText("Siempre");
        radioSiemprePregunta25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta25ActionPerformed(evt);
            }
        });
        panelPregunta25.add(radioSiemprePregunta25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta25, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente9ActionPerformed
       if(!validar.preguntaUno || !validar.preguntaDos || !validar.preguntaTres ){
             JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");
        
        
        }
        else {
         cuestionarioNueve.retornarSubtotal();
        cuestionarioNueve.retornarTotal();
        
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioNueve.retornarSubtotal() );
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioNueve.retornarTotal() );
        VentanaPreguntas10 ventanaDiez = new VentanaPreguntas10(cuestionarioNueve.retornarTotal());
        ventanaDiez.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnSiguiente9ActionPerformed

    private void radioNuncaPregunta25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta25ActionPerformed
        if(radioNuncaPregunta25.isSelected() == true){
            cuestionarioNueve.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioNueve.getValorPreguntaUno());
        
        
        }
    }//GEN-LAST:event_radioNuncaPregunta25ActionPerformed

    private void radioVecesPregunta25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta25ActionPerformed
         if(radioVecesPregunta25.isSelected() == true){
            cuestionarioNueve.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioNueve.getValorPreguntaUno());
        
        
        }
    }//GEN-LAST:event_radioVecesPregunta25ActionPerformed

    private void radioSiemprePregunta25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta25ActionPerformed
        if(radioSiemprePregunta25.isSelected() == true){
            cuestionarioNueve.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioNueve.getValorPreguntaUno());
        
        
        }
    }//GEN-LAST:event_radioSiemprePregunta25ActionPerformed

    private void radioNuncaPregunta26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta26ActionPerformed
        if(radioNuncaPregunta26.isSelected() == true){
            cuestionarioNueve.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta dos es " + cuestionarioNueve.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioNuncaPregunta26ActionPerformed

    private void radioVecesPregunta26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta26ActionPerformed
          if(radioVecesPregunta26.isSelected() == true){
            cuestionarioNueve.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta dos es " + cuestionarioNueve.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioVecesPregunta26ActionPerformed

    private void radioSiemprePregunta26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta26ActionPerformed
         if(radioSiemprePregunta26.isSelected() == true){
            cuestionarioNueve.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta dos es " + cuestionarioNueve.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioSiemprePregunta26ActionPerformed

    private void radioNuncaPregunta27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta27ActionPerformed
       if(radioNuncaPregunta27.isSelected()){
           cuestionarioNueve.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es  "+cuestionarioNueve.getValorPreguntaTres() );
       
       
       }
    }//GEN-LAST:event_radioNuncaPregunta27ActionPerformed

    private void radioVecesPregunta27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta27ActionPerformed
       if(radioVecesPregunta27.isSelected()){
           cuestionarioNueve.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es  "+cuestionarioNueve.getValorPreguntaTres() );
       
       
       }
    }//GEN-LAST:event_radioVecesPregunta27ActionPerformed

    private void radioSiemprePregunta27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta27ActionPerformed
         if(radioSiemprePregunta27.isSelected()){
           cuestionarioNueve.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es  "+cuestionarioNueve.getValorPreguntaTres() );
       
       
       }
    }//GEN-LAST:event_radioSiemprePregunta27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDosPregunta27;
    private javax.swing.JLabel labelPregunta25;
    private javax.swing.JLabel labelPregunta26;
    private javax.swing.JLabel labelPregunta27;
    private javax.swing.JLabel labelPregunta9;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta25;
    private javax.swing.JPanel panelPregunta26;
    private javax.swing.JPanel panelPregunta27;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta25;
    private javax.swing.JRadioButton radioNuncaPregunta26;
    private javax.swing.JRadioButton radioNuncaPregunta27;
    private javax.swing.JRadioButton radioSiemprePregunta25;
    private javax.swing.JRadioButton radioSiemprePregunta26;
    private javax.swing.JRadioButton radioSiemprePregunta27;
    private javax.swing.JRadioButton radioVecesPregunta25;
    private javax.swing.JRadioButton radioVecesPregunta26;
    private javax.swing.JRadioButton radioVecesPregunta27;
    // End of variables declaration//GEN-END:variables
}
