/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas7 extends javax.swing.JFrame {
public int valorPasado;
Cuestionario cuestionarioSiete;
Validacion validar;
    public VentanaPreguntas7() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }
    
    public VentanaPreguntas7(int valorPasado) {
        this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }
    
    public void cargarClases(int valorPasado){
    cuestionarioSiete = new Cuestionario(valorPasado);
    validar = new Validacion();
    
    
    }

    public void cargarRadioBotones() {
        cargarRadioPregunta19();
        cargarRadioPregunta20();
        cargarRadioPregunta21();

    }

    public void cargarRadioPregunta19() {
        ButtonGroup grupoPregunta19 = new ButtonGroup();
        grupoPregunta19.add(radioNuncaPregunta19);
        grupoPregunta19.add(radioVecesPregunta19);
        grupoPregunta19.add(radioSiemprePregunta19);

    }

    public void cargarRadioPregunta20() {
        ButtonGroup grupoPregunta20 = new ButtonGroup();
        grupoPregunta20.add(radioNuncaPregunta20);
        grupoPregunta20.add(radioVecesPregunta20);
        grupoPregunta20.add(radioSiemprePregunta20);

    }

    public void cargarRadioPregunta21() {
        ButtonGroup grupoPregunta21 = new ButtonGroup();
        grupoPregunta21.add(radioNuncaPregunta21);
        grupoPregunta21.add(radioVecesPregunta21);
        grupoPregunta21.add(radioSiemprePregunta21);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelPreguntaSeis = new javax.swing.JLabel();
        btnSiguiente7 = new javax.swing.JButton();
        panelPregunta21 = new javax.swing.JPanel();
        labelPregunta21 = new javax.swing.JLabel();
        radioNuncaPregunta21 = new javax.swing.JRadioButton();
        radioVecesPregunta21 = new javax.swing.JRadioButton();
        radioSiemprePregunta21 = new javax.swing.JRadioButton();
        panelPregunta20 = new javax.swing.JPanel();
        labelPregunta20 = new javax.swing.JLabel();
        radioNuncaPregunta20 = new javax.swing.JRadioButton();
        radioVecesPregunta20 = new javax.swing.JRadioButton();
        radioSiemprePregunta20 = new javax.swing.JRadioButton();
        panelPregunta19 = new javax.swing.JPanel();
        labelPregunta19 = new javax.swing.JLabel();
        radioNuncaPregunta19 = new javax.swing.JRadioButton();
        radioVecesPregunta19 = new javax.swing.JRadioButton();
        radioSiemprePregunta19 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelPreguntaSeis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPreguntaSeis.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelPreguntaSeis, gridBagConstraints);

        btnSiguiente7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente7.setText("Siguiente");
        btnSiguiente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSiguiente7, gridBagConstraints);

        panelPregunta21.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta21.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta21.setText("21. Tengo confianza en mí mismo, en lo que soy capaz de hacer, pensar y sentir. ");
        panelPregunta21.add(labelPregunta21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta21.setText("Nunca");
        radioNuncaPregunta21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta21ActionPerformed(evt);
            }
        });
        panelPregunta21.add(radioNuncaPregunta21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta21.setText("Algunas veces");
        radioVecesPregunta21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta21ActionPerformed(evt);
            }
        });
        panelPregunta21.add(radioVecesPregunta21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta21.setText("Siempre");
        radioSiemprePregunta21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta21ActionPerformed(evt);
            }
        });
        panelPregunta21.add(radioSiemprePregunta21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta21, gridBagConstraints);

        panelPregunta20.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta20.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta20.setText("20. Soy capaz de sonreír.");
        panelPregunta20.add(labelPregunta20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta20.setText("Nunca");
        radioNuncaPregunta20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta20ActionPerformed(evt);
            }
        });
        panelPregunta20.add(radioNuncaPregunta20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta20.setText("Algunas veces");
        radioVecesPregunta20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta20ActionPerformed(evt);
            }
        });
        panelPregunta20.add(radioVecesPregunta20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta20.setText("Siempre");
        radioSiemprePregunta20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta20ActionPerformed(evt);
            }
        });
        panelPregunta20.add(radioSiemprePregunta20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta20, gridBagConstraints);

        panelPregunta19.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta19.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta19.setText("19. Hay cosas que no me gusta hacer pero sé que hay que hacerlas y las hago. ");
        panelPregunta19.add(labelPregunta19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta19.setText("Nunca");
        radioNuncaPregunta19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta19ActionPerformed(evt);
            }
        });
        panelPregunta19.add(radioNuncaPregunta19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta19.setText("Algunas veces");
        radioVecesPregunta19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta19ActionPerformed(evt);
            }
        });
        panelPregunta19.add(radioVecesPregunta19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta19.setText("Siempre");
        radioSiemprePregunta19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta19ActionPerformed(evt);
            }
        });
        panelPregunta19.add(radioSiemprePregunta19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta19, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente7ActionPerformed
        if(!validar.preguntaUno || !validar.preguntaDos || !validar.preguntaTres ){
             JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");
        
        
        }
        else {
         cuestionarioSiete.retornarSubtotal();
        cuestionarioSiete.retornarTotal();
        
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioSiete.retornarSubtotal() );
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioSiete.retornarTotal() );
        VentanaPreguntas8 ventanaOcho = new VentanaPreguntas8(cuestionarioSiete.retornarTotal());
        ventanaOcho.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnSiguiente7ActionPerformed

    private void radioNuncaPregunta19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta19ActionPerformed
        if(radioNuncaPregunta19.isSelected() == true){
            cuestionarioSiete.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor de pregunta uno es " + cuestionarioSiete.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioNuncaPregunta19ActionPerformed

    private void radioVecesPregunta19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta19ActionPerformed
        if(radioVecesPregunta19.isSelected() == true){
            cuestionarioSiete.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor de pregunta uno es " + cuestionarioSiete.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioVecesPregunta19ActionPerformed

    private void radioSiemprePregunta19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta19ActionPerformed
       if(radioSiemprePregunta19.isSelected() == true){
            cuestionarioSiete.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor de pregunta uno es " + cuestionarioSiete.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioSiemprePregunta19ActionPerformed

    private void radioNuncaPregunta20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta20ActionPerformed
        if(radioNuncaPregunta20.isSelected() == true){
            cuestionarioSiete.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El calor de la pregunta dos es " + cuestionarioSiete.getValorPreguntaDos());
        
        
        }
    }//GEN-LAST:event_radioNuncaPregunta20ActionPerformed

    private void radioVecesPregunta20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta20ActionPerformed
          if(radioVecesPregunta20.isSelected() == true){
            cuestionarioSiete.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El calor de la pregunta dos es " + cuestionarioSiete.getValorPreguntaDos());
        
        
        }
    }//GEN-LAST:event_radioVecesPregunta20ActionPerformed

    private void radioSiemprePregunta20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta20ActionPerformed
          if(radioSiemprePregunta20.isSelected() == true){
            cuestionarioSiete.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El calor de la pregunta dos es " + cuestionarioSiete.getValorPreguntaDos());
        
        
        }
    }//GEN-LAST:event_radioSiemprePregunta20ActionPerformed

    private void radioNuncaPregunta21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta21ActionPerformed
        if(radioNuncaPregunta21.isSelected() == true){
            cuestionarioSiete.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, "EL valor de la pregunta 3 es " + cuestionarioSiete.getValorPreguntaTres());
        
        }
    }//GEN-LAST:event_radioNuncaPregunta21ActionPerformed

    private void radioVecesPregunta21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta21ActionPerformed
        if(radioVecesPregunta21.isSelected() == true){
            cuestionarioSiete.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, "EL valor de la pregunta 3 es " + cuestionarioSiete.getValorPreguntaTres());
        
        }
    }//GEN-LAST:event_radioVecesPregunta21ActionPerformed

    private void radioSiemprePregunta21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta21ActionPerformed
         if(radioSiemprePregunta21.isSelected() == true){
            cuestionarioSiete.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, "EL valor de la pregunta 3 es " + cuestionarioSiete.getValorPreguntaTres());
        
        }
    }//GEN-LAST:event_radioSiemprePregunta21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta19;
    private javax.swing.JLabel labelPregunta20;
    private javax.swing.JLabel labelPregunta21;
    private javax.swing.JLabel labelPreguntaSeis;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta19;
    private javax.swing.JPanel panelPregunta20;
    private javax.swing.JPanel panelPregunta21;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta19;
    private javax.swing.JRadioButton radioNuncaPregunta20;
    private javax.swing.JRadioButton radioNuncaPregunta21;
    private javax.swing.JRadioButton radioSiemprePregunta19;
    private javax.swing.JRadioButton radioSiemprePregunta20;
    private javax.swing.JRadioButton radioSiemprePregunta21;
    private javax.swing.JRadioButton radioVecesPregunta19;
    private javax.swing.JRadioButton radioVecesPregunta20;
    private javax.swing.JRadioButton radioVecesPregunta21;
    // End of variables declaration//GEN-END:variables
}
