/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas5 extends javax.swing.JFrame {

    public int valorPasado;
    Cuestionario cuestionarioCinco;
    Validacion validar;

    public VentanaPreguntas5() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }

    public VentanaPreguntas5(int valorPasado) {
        this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }

    public void cargarClases(int valorPasado) {
        cuestionarioCinco = new Cuestionario(valorPasado);
        validar = new Validacion();

    }

    public void cargarRadioBotones() {
        cargarRadioPreguntaTrece();
        cargarRadioPreguntaCatorce();
        cargarRadioPreguntaQuince();

    }

    public void cargarRadioPreguntaTrece() {
        ButtonGroup grupoPreguntaTrece = new ButtonGroup();
        grupoPreguntaTrece.add(radioNuncaPregunta13);
        grupoPreguntaTrece.add(radioVecesPregunta13);
        grupoPreguntaTrece.add(radioSiemprePregunta13);

    }

    public void cargarRadioPreguntaCatorce() {
        ButtonGroup grupoPreguntaCatorce = new ButtonGroup();
        grupoPreguntaCatorce.add(radioNuncaPregunta14);
        grupoPreguntaCatorce.add(radioVecesPregunta14);
        grupoPreguntaCatorce.add(radioSiemprePregunta14);

    }

    public void cargarRadioPreguntaQuince() {
        ButtonGroup grupoPreguntaQuince = new ButtonGroup();
        grupoPreguntaQuince.add(radioNuncaPregunta15);
        grupoPreguntaQuince.add(radioVecesPregunta15);
        grupoPreguntaQuince.add(radioSiemprePregunta15);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelTItulo5 = new javax.swing.JLabel();
        btnSIguiente5 = new javax.swing.JButton();
        panelPregunta15 = new javax.swing.JPanel();
        labelPregunta15 = new javax.swing.JLabel();
        radioNuncaPregunta15 = new javax.swing.JRadioButton();
        radioVecesPregunta15 = new javax.swing.JRadioButton();
        radioSiemprePregunta15 = new javax.swing.JRadioButton();
        panelPregunta14 = new javax.swing.JPanel();
        labelPregunta14 = new javax.swing.JLabel();
        radioNuncaPregunta14 = new javax.swing.JRadioButton();
        radioVecesPregunta14 = new javax.swing.JRadioButton();
        radioSiemprePregunta14 = new javax.swing.JRadioButton();
        panelPregunta13 = new javax.swing.JPanel();
        labelPregunta13 = new javax.swing.JLabel();
        radioNuncaPregunta13 = new javax.swing.JRadioButton();
        radioVecesPregunta13 = new javax.swing.JRadioButton();
        radioSiemprePregunta13 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 620));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelTItulo5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTItulo5.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelTItulo5, gridBagConstraints);

        btnSIguiente5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSIguiente5.setText("Siguiente");
        btnSIguiente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIguiente5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSIguiente5, gridBagConstraints);

        panelPregunta15.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta15.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta15.setText("15. Soy capaz de quitarme de la mente las preocupaciones que me obsesionan. ");
        panelPregunta15.add(labelPregunta15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta15.setText("Nunca");
        radioNuncaPregunta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta15ActionPerformed(evt);
            }
        });
        panelPregunta15.add(radioNuncaPregunta15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta15.setText("Algunas veces");
        radioVecesPregunta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta15ActionPerformed(evt);
            }
        });
        panelPregunta15.add(radioVecesPregunta15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta15.setText("Siempre");
        radioSiemprePregunta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta15ActionPerformed(evt);
            }
        });
        panelPregunta15.add(radioSiemprePregunta15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta15, gridBagConstraints);

        panelPregunta14.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta14.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta14.setText("14. Cuando me critican por algo que es justo lo acepto porque tienen razón. ");
        panelPregunta14.add(labelPregunta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta14.setText("Nunca");
        radioNuncaPregunta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta14ActionPerformed(evt);
            }
        });
        panelPregunta14.add(radioNuncaPregunta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta14.setText("Algunas veces");
        radioVecesPregunta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta14ActionPerformed(evt);
            }
        });
        panelPregunta14.add(radioVecesPregunta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta14.setText("Siempre");
        radioSiemprePregunta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta14ActionPerformed(evt);
            }
        });
        panelPregunta14.add(radioSiemprePregunta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta14, gridBagConstraints);

        panelPregunta13.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta13.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta13.setText("13. Cuando alguien me critica injustamente me defiendo adecuadamente con el diálogo. ");
        panelPregunta13.add(labelPregunta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta13.setText("Nunca");
        radioNuncaPregunta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta13ActionPerformed(evt);
            }
        });
        panelPregunta13.add(radioNuncaPregunta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta13.setText("Algunas veces");
        radioVecesPregunta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta13ActionPerformed(evt);
            }
        });
        panelPregunta13.add(radioVecesPregunta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta13.setText("SIempre");
        radioSiemprePregunta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta13ActionPerformed(evt);
            }
        });
        panelPregunta13.add(radioSiemprePregunta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSIguiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIguiente5ActionPerformed
         if (validar.preguntaUno == false || validar.preguntaDos == false || validar.preguntaTres == false) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");

        } else {
            cuestionarioCinco.retornarSubtotal();
            cuestionarioCinco.retornarTotal();

//            JOptionPane.showMessageDialog(null, "El subtotal es " + cuestionarioCinco.retornarSubtotal());
//            JOptionPane.showMessageDialog(null, "El total " + cuestionarioCinco.retornarTotal());
            VentanaPreguntas6 ventanaSeis = new VentanaPreguntas6(cuestionarioCinco.retornarTotal());
            ventanaSeis.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_btnSIguiente5ActionPerformed

    private void radioNuncaPregunta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta13ActionPerformed
        if (radioNuncaPregunta13.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaUno());

        }
    }//GEN-LAST:event_radioNuncaPregunta13ActionPerformed

    private void radioVecesPregunta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta13ActionPerformed
        if (radioVecesPregunta13.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaUno());

        }
    }//GEN-LAST:event_radioVecesPregunta13ActionPerformed

    private void radioSiemprePregunta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta13ActionPerformed
        if (radioSiemprePregunta13.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaUno());

        }
    }//GEN-LAST:event_radioSiemprePregunta13ActionPerformed

    private void radioNuncaPregunta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta14ActionPerformed
        if (radioNuncaPregunta14.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaDos());

        }
    }//GEN-LAST:event_radioNuncaPregunta14ActionPerformed

    private void radioVecesPregunta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta14ActionPerformed
        if (radioVecesPregunta14.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
           // JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaDos());

        }
    }//GEN-LAST:event_radioVecesPregunta14ActionPerformed

    private void radioSiemprePregunta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta14ActionPerformed
        if (radioSiemprePregunta14.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaDos());

        }
    }//GEN-LAST:event_radioSiemprePregunta14ActionPerformed

    private void radioNuncaPregunta15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta15ActionPerformed
        if (radioNuncaPregunta15.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaTres());

        }
    }//GEN-LAST:event_radioNuncaPregunta15ActionPerformed

    private void radioVecesPregunta15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta15ActionPerformed
        if (radioVecesPregunta15.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaTres = true;
           // JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaTres());

        }
    }//GEN-LAST:event_radioVecesPregunta15ActionPerformed

    private void radioSiemprePregunta15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta15ActionPerformed
        if (radioSiemprePregunta15.isSelected() == true) {
            cuestionarioCinco.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, cuestionarioCinco.getValorPreguntaTres());

        }
    }//GEN-LAST:event_radioSiemprePregunta15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSIguiente5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta13;
    private javax.swing.JLabel labelPregunta14;
    private javax.swing.JLabel labelPregunta15;
    private javax.swing.JLabel labelTItulo5;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta13;
    private javax.swing.JPanel panelPregunta14;
    private javax.swing.JPanel panelPregunta15;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta13;
    private javax.swing.JRadioButton radioNuncaPregunta14;
    private javax.swing.JRadioButton radioNuncaPregunta15;
    private javax.swing.JRadioButton radioSiemprePregunta13;
    private javax.swing.JRadioButton radioSiemprePregunta14;
    private javax.swing.JRadioButton radioSiemprePregunta15;
    private javax.swing.JRadioButton radioVecesPregunta13;
    private javax.swing.JRadioButton radioVecesPregunta14;
    private javax.swing.JRadioButton radioVecesPregunta15;
    // End of variables declaration//GEN-END:variables
}
