/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas6 extends javax.swing.JFrame {
public int valorPasado;
Cuestionario cuestionarioSeis;
Validacion validar;
    
    public VentanaPreguntas6() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }
    
    public VentanaPreguntas6(int valorPasado) {
        this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }

    public void cargarRadioBotones() {
        cargarRadioPregunta16();
        cargarRadioPregunta17();
        cargarRadioPregunta18();

    }
    
    public void cargarClases(int valorPasado){
    cuestionarioSeis = new Cuestionario(valorPasado);
    validar = new Validacion();
    
    }

    public void cargarRadioPregunta16() {
        ButtonGroup grupoPregunta16 = new ButtonGroup();
        grupoPregunta16.add(radioNuncaPregunta16);
        grupoPregunta16.add(radioVecesPregunta16);
        grupoPregunta16.add(radioSiemprePregunta16);

    }
    public void cargarRadioPregunta17() {
        ButtonGroup grupoPregunta17 = new ButtonGroup();
        grupoPregunta17.add(radioNuncaPregunta17);
        grupoPregunta17.add(radioVecesPregunta17);
        grupoPregunta17.add(radioSiemprePregunta17);

    }
    public void cargarRadioPregunta18() {
        ButtonGroup grupoPregunta18 = new ButtonGroup();
        grupoPregunta18.add(radioNuncaPregunta18);
        grupoPregunta18.add(radioVecesPregunta18);
        grupoPregunta18.add(radioSiemprePregunta18);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelTItulo6 = new javax.swing.JLabel();
        btnSIguienteCinco = new javax.swing.JButton();
        panelPregunta18 = new javax.swing.JPanel();
        labelPregunta18 = new javax.swing.JLabel();
        radioNuncaPregunta18 = new javax.swing.JRadioButton();
        radioVecesPregunta18 = new javax.swing.JRadioButton();
        radioSiemprePregunta18 = new javax.swing.JRadioButton();
        panelPregunta17 = new javax.swing.JPanel();
        labelPregunta17 = new javax.swing.JLabel();
        radioNuncaPregunta17 = new javax.swing.JRadioButton();
        radioVecesPregunta17 = new javax.swing.JRadioButton();
        radioSiemprePregunta17 = new javax.swing.JRadioButton();
        panelPregunta16 = new javax.swing.JPanel();
        labelPregunta16 = new javax.swing.JLabel();
        labelPreguntaDieciseisDos = new javax.swing.JLabel();
        radioNuncaPregunta16 = new javax.swing.JRadioButton();
        radioVecesPregunta16 = new javax.swing.JRadioButton();
        radioSiemprePregunta16 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelTItulo6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTItulo6.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelTItulo6, gridBagConstraints);

        btnSIguienteCinco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSIguienteCinco.setText("Siguiente");
        btnSIguienteCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIguienteCincoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSIguienteCinco, gridBagConstraints);

        panelPregunta18.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta18.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta18.setText("18. Soy capaz de divertirme y pasármelo bien allí donde esté. ");
        panelPregunta18.add(labelPregunta18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta18.setText("Nunca");
        radioNuncaPregunta18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta18ActionPerformed(evt);
            }
        });
        panelPregunta18.add(radioNuncaPregunta18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta18.setText("Algunas veces");
        radioVecesPregunta18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta18ActionPerformed(evt);
            }
        });
        panelPregunta18.add(radioVecesPregunta18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta18.setText("Siempre");
        radioSiemprePregunta18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta18ActionPerformed(evt);
            }
        });
        panelPregunta18.add(radioSiemprePregunta18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta18, gridBagConstraints);

        panelPregunta17.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta17.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPregunta17.setText("17. Valoro las cosas buenas que hago.");
        panelPregunta17.add(labelPregunta17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta17.setText("Nunca");
        radioNuncaPregunta17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta17ActionPerformed(evt);
            }
        });
        panelPregunta17.add(radioNuncaPregunta17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta17.setText("Algunas veces");
        radioVecesPregunta17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta17ActionPerformed(evt);
            }
        });
        panelPregunta17.add(radioVecesPregunta17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta17.setText("Siempre");
        radioSiemprePregunta17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta17ActionPerformed(evt);
            }
        });
        panelPregunta17.add(radioSiemprePregunta17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta17, gridBagConstraints);

        panelPregunta16.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta16.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta16.setText("16. Me doy cuenta de lo que dicen, piensan y sienten las personas más cercanas a mí (amigos, ");
        panelPregunta16.add(labelPregunta16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        labelPreguntaDieciseisDos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPreguntaDieciseisDos.setText("compañeros, familiares…)");
        panelPregunta16.add(labelPreguntaDieciseisDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        radioNuncaPregunta16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta16.setText("Nunca");
        radioNuncaPregunta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta16ActionPerformed(evt);
            }
        });
        panelPregunta16.add(radioNuncaPregunta16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta16.setText("Algunas veces");
        radioVecesPregunta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta16ActionPerformed(evt);
            }
        });
        panelPregunta16.add(radioVecesPregunta16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta16.setText("SIempre");
        radioSiemprePregunta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta16ActionPerformed(evt);
            }
        });
        panelPregunta16.add(radioSiemprePregunta16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSIguienteCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIguienteCincoActionPerformed
        if(!validar.preguntaUno || !validar.preguntaDos || !validar.preguntaTres ){
             JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");
        
        }
        else{
        cuestionarioSeis.retornarSubtotal();
        cuestionarioSeis.retornarTotal();
//        
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioSeis.retornarSubtotal() );
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioSeis.retornarTotal() );
        VentanaPreguntas7 ventanaSiete = new VentanaPreguntas7(cuestionarioSeis.retornarTotal());
        ventanaSiete.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnSIguienteCincoActionPerformed

    private void radioNuncaPregunta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta16ActionPerformed
        if(radioNuncaPregunta16.isSelected() == true){
            cuestionarioSeis.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "Valor de la pregunta 1 es" + cuestionarioSeis.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioNuncaPregunta16ActionPerformed

    private void radioVecesPregunta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta16ActionPerformed
         if(radioVecesPregunta16.isSelected() == true){
            cuestionarioSeis.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "Valor de la pregunta 1 es" + cuestionarioSeis.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioVecesPregunta16ActionPerformed

    private void radioSiemprePregunta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta16ActionPerformed
         if(radioSiemprePregunta16.isSelected() == true){
            cuestionarioSeis.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "Valor de la pregunta 1 es" + cuestionarioSeis.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioSiemprePregunta16ActionPerformed

    private void radioNuncaPregunta17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta17ActionPerformed
        if(radioNuncaPregunta17.isSelected() == true){
            cuestionarioSeis.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta 2 es " + cuestionarioSeis.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioNuncaPregunta17ActionPerformed

    private void radioVecesPregunta17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta17ActionPerformed
        if(radioVecesPregunta17.isSelected() == true){
            cuestionarioSeis.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta 2 es " + cuestionarioSeis.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioVecesPregunta17ActionPerformed

    private void radioSiemprePregunta17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta17ActionPerformed
        if(radioSiemprePregunta17.isSelected() == true){
            cuestionarioSeis.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta 2 es " + cuestionarioSeis.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioSiemprePregunta17ActionPerformed

    private void radioNuncaPregunta18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta18ActionPerformed
       if(radioNuncaPregunta18.isSelected() == true){
           cuestionarioSeis.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 3 es " + cuestionarioSeis.getValorPreguntaTres());
       
       }
    }//GEN-LAST:event_radioNuncaPregunta18ActionPerformed

    private void radioVecesPregunta18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta18ActionPerformed
         if(radioVecesPregunta18.isSelected() == true){
           cuestionarioSeis.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 3 es " + cuestionarioSeis.getValorPreguntaTres());
       
       }
    }//GEN-LAST:event_radioVecesPregunta18ActionPerformed

    private void radioSiemprePregunta18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta18ActionPerformed
        if(radioSiemprePregunta18.isSelected() == true){
           cuestionarioSeis.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 3 es " + cuestionarioSeis.getValorPreguntaTres());
       
       }
    }//GEN-LAST:event_radioSiemprePregunta18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSIguienteCinco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta16;
    private javax.swing.JLabel labelPregunta17;
    private javax.swing.JLabel labelPregunta18;
    private javax.swing.JLabel labelPreguntaDieciseisDos;
    private javax.swing.JLabel labelTItulo6;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta16;
    private javax.swing.JPanel panelPregunta17;
    private javax.swing.JPanel panelPregunta18;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta16;
    private javax.swing.JRadioButton radioNuncaPregunta17;
    private javax.swing.JRadioButton radioNuncaPregunta18;
    private javax.swing.JRadioButton radioSiemprePregunta16;
    private javax.swing.JRadioButton radioSiemprePregunta17;
    private javax.swing.JRadioButton radioSiemprePregunta18;
    private javax.swing.JRadioButton radioVecesPregunta16;
    private javax.swing.JRadioButton radioVecesPregunta17;
    private javax.swing.JRadioButton radioVecesPregunta18;
    // End of variables declaration//GEN-END:variables
}
