/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas12 extends javax.swing.JFrame {
public int valorPasado;
Cuestionario cuestionarioDoce;
Validacion validar;
    public VentanaPreguntas12() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }
     public VentanaPreguntas12(int valorPasado) {
         this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }
     
     public void cargarClases(int valorPasado){
        cuestionarioDoce = new Cuestionario(valorPasado);
        validar = new Validacion();
    
    }

    public void cargarRadioBotones() {
        cargarRadioPregunta19();
        cargarRadioPregunta20();
        cargarRadioPregunta21();

    }

    public void cargarRadioPregunta19() {
        ButtonGroup grupoPregunta19 = new ButtonGroup();
        grupoPregunta19.add(radioNuncaPregunta34);
        grupoPregunta19.add(radioVecesPregunta34);
        grupoPregunta19.add(radioSiemprePregunta34);

    }

    public void cargarRadioPregunta20() {
        ButtonGroup grupoPregunta20 = new ButtonGroup();
        grupoPregunta20.add(radioNuncaPregunta35);
        grupoPregunta20.add(radioVecesPregunta35);
        grupoPregunta20.add(radioSiemprePregunta35);

    }

    public void cargarRadioPregunta21() {
        ButtonGroup grupoPregunta21 = new ButtonGroup();
        grupoPregunta21.add(radioNuncaPregunta36);
        grupoPregunta21.add(radioVecesPregunta36);
        grupoPregunta21.add(radioSiemprePregunta36);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelPregunta12 = new javax.swing.JLabel();
        btnSiguiente12 = new javax.swing.JButton();
        panelPregunta36 = new javax.swing.JPanel();
        radioNuncaPregunta36 = new javax.swing.JRadioButton();
        radioVecesPregunta36 = new javax.swing.JRadioButton();
        radioSiemprePregunta36 = new javax.swing.JRadioButton();
        labelPregunta36 = new javax.swing.JLabel();
        panelPregunta35 = new javax.swing.JPanel();
        labelPregunta35 = new javax.swing.JLabel();
        radioNuncaPregunta35 = new javax.swing.JRadioButton();
        radioVecesPregunta35 = new javax.swing.JRadioButton();
        radioSiemprePregunta35 = new javax.swing.JRadioButton();
        panelPregunta34 = new javax.swing.JPanel();
        radioNuncaPregunta34 = new javax.swing.JRadioButton();
        radioVecesPregunta34 = new javax.swing.JRadioButton();
        radioSiemprePregunta34 = new javax.swing.JRadioButton();
        labelPregunta34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelPregunta12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPregunta12.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelPregunta12, gridBagConstraints);

        btnSiguiente12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente12.setText("Siguiente");
        btnSiguiente12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente12ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSiguiente12, gridBagConstraints);

        panelPregunta36.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta36.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioNuncaPregunta36.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta36.setText("Nunca");
        radioNuncaPregunta36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta36ActionPerformed(evt);
            }
        });
        panelPregunta36.add(radioNuncaPregunta36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta36.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta36.setText("Algunas veces");
        radioVecesPregunta36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta36ActionPerformed(evt);
            }
        });
        panelPregunta36.add(radioVecesPregunta36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta36.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta36.setText("Siempre");
        radioSiemprePregunta36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta36ActionPerformed(evt);
            }
        });
        panelPregunta36.add(radioSiemprePregunta36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelPregunta36.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta36.setText("36. Sé qué pensamientos son capaces de hacerme sentir feliz, triste, enfadado, altruista, angustiado. ");
        panelPregunta36.add(labelPregunta36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta36, gridBagConstraints);

        panelPregunta35.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta35.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta35.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta35.setText("35. Soy creativo, tengo ideas originales y las desarrollo. ");
        panelPregunta35.add(labelPregunta35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta35.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta35.setText("Nunca");
        radioNuncaPregunta35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta35ActionPerformed(evt);
            }
        });
        panelPregunta35.add(radioNuncaPregunta35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta35.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta35.setText("Algunas veces");
        radioVecesPregunta35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta35ActionPerformed(evt);
            }
        });
        panelPregunta35.add(radioVecesPregunta35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta35.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta35.setText("Siempre");
        radioSiemprePregunta35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta35ActionPerformed(evt);
            }
        });
        panelPregunta35.add(radioSiemprePregunta35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta35, gridBagConstraints);

        panelPregunta34.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta34.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioNuncaPregunta34.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta34.setText("Nunca");
        radioNuncaPregunta34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta34ActionPerformed(evt);
            }
        });
        panelPregunta34.add(radioNuncaPregunta34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta34.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta34.setText("Algunas veces");
        radioVecesPregunta34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta34ActionPerformed(evt);
            }
        });
        panelPregunta34.add(radioVecesPregunta34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta34.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta34.setText("Siempre");
        radioSiemprePregunta34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta34ActionPerformed(evt);
            }
        });
        panelPregunta34.add(radioSiemprePregunta34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelPregunta34.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta34.setText("34. Sé cuáles son mis defectos y cómo cambiarlos");
        panelPregunta34.add(labelPregunta34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta34, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente12ActionPerformed
         if(!validar.preguntaUno || !validar.preguntaDos || !validar.preguntaTres ){
             JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");
        
        
        }
        else {
         cuestionarioDoce.retornarSubtotal();
        cuestionarioDoce.retornarTotal();
        
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioDoce.retornarSubtotal() );
//        JOptionPane.showMessageDialog(null, "El total es "+cuestionarioDoce.retornarTotal() );
        VentanaPreguntas13 ventanaTrece = new VentanaPreguntas13(cuestionarioDoce.retornarTotal());
        ventanaTrece.setVisible(true);
        this.dispose();
        
        }
    }//GEN-LAST:event_btnSiguiente12ActionPerformed

    private void radioNuncaPregunta34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta34ActionPerformed
        if(radioNuncaPregunta34.isSelected() == true){
            cuestionarioDoce.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
           // JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioDoce.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioNuncaPregunta34ActionPerformed

    private void radioVecesPregunta34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta34ActionPerformed
       if(radioVecesPregunta34.isSelected() == true){
            cuestionarioDoce.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
           // JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioDoce.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioVecesPregunta34ActionPerformed

    private void radioSiemprePregunta34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta34ActionPerformed
        if(radioSiemprePregunta34.isSelected() == true){
            cuestionarioDoce.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta uno es "+ cuestionarioDoce.getValorPreguntaUno());
        
        }
    }//GEN-LAST:event_radioSiemprePregunta34ActionPerformed

    private void radioNuncaPregunta35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta35ActionPerformed
        if(radioNuncaPregunta35.isSelected() == true){
           cuestionarioDoce.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
           validar.preguntaDos = true;
          // JOptionPane.showMessageDialog(null, "El valor de la pregunta dos "+ cuestionarioDoce.getValorPreguntaDos());
       
       }
    }//GEN-LAST:event_radioNuncaPregunta35ActionPerformed

    private void radioVecesPregunta35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta35ActionPerformed
         if(radioVecesPregunta35.isSelected() == true){
           cuestionarioDoce.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
           validar.preguntaDos = true;
          // JOptionPane.showMessageDialog(null, "El valor de la pregunta dos "+ cuestionarioDoce.getValorPreguntaDos());
       
       }
    }//GEN-LAST:event_radioVecesPregunta35ActionPerformed

    private void radioSiemprePregunta35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta35ActionPerformed
         if(radioSiemprePregunta35.isSelected() == true){
           cuestionarioDoce.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
           validar.preguntaDos = true;
          // JOptionPane.showMessageDialog(null, "El valor de la pregunta dos "+ cuestionarioDoce.getValorPreguntaDos());
       
       }
    }//GEN-LAST:event_radioSiemprePregunta35ActionPerformed

    private void radioNuncaPregunta36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta36ActionPerformed
       if(radioNuncaPregunta36.isSelected() == true){
            cuestionarioDoce.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
            validar.preguntaTres = true;
           // JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es "+ cuestionarioDoce.getValorPreguntaTres());
        
        
        }
    }//GEN-LAST:event_radioNuncaPregunta36ActionPerformed

    private void radioVecesPregunta36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta36ActionPerformed
        if(radioVecesPregunta36.isSelected() == true){
            cuestionarioDoce.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaTres = true;
           // JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es "+ cuestionarioDoce.getValorPreguntaTres());
        
        
        }
    }//GEN-LAST:event_radioVecesPregunta36ActionPerformed

    private void radioSiemprePregunta36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta36ActionPerformed
        if(radioSiemprePregunta36.isSelected() == true){
            cuestionarioDoce.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta tres es "+ cuestionarioDoce.getValorPreguntaTres());
        
        
        }
    }//GEN-LAST:event_radioSiemprePregunta36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta12;
    private javax.swing.JLabel labelPregunta34;
    private javax.swing.JLabel labelPregunta35;
    private javax.swing.JLabel labelPregunta36;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta34;
    private javax.swing.JPanel panelPregunta35;
    private javax.swing.JPanel panelPregunta36;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta34;
    private javax.swing.JRadioButton radioNuncaPregunta35;
    private javax.swing.JRadioButton radioNuncaPregunta36;
    private javax.swing.JRadioButton radioSiemprePregunta34;
    private javax.swing.JRadioButton radioSiemprePregunta35;
    private javax.swing.JRadioButton radioSiemprePregunta36;
    private javax.swing.JRadioButton radioVecesPregunta34;
    private javax.swing.JRadioButton radioVecesPregunta35;
    private javax.swing.JRadioButton radioVecesPregunta36;
    // End of variables declaration//GEN-END:variables
}
