/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas8 extends javax.swing.JFrame {

    public int valorPasado;
    Cuestionario cuestionarioOcho;
    Validacion validar;

    public VentanaPreguntas8() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }
    
    
    public VentanaPreguntas8( int valorPasado) {
        this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));

    }
    
    public void cargarClases(int valorPasado){
        cuestionarioOcho = new Cuestionario(valorPasado);
        validar = new Validacion();
    
    
    }

    public void cargarRadioBotones() {
        cargarRadioPregunta19();
        cargarRadioPregunta20();
        cargarRadioPregunta21();

    }

    public void cargarRadioPregunta19() {
        ButtonGroup grupoPregunta19 = new ButtonGroup();
        grupoPregunta19.add(radioNuncaPregunta22);
        grupoPregunta19.add(radioVecesPregunta22);
        grupoPregunta19.add(radioSiemprePregunta22);

    }

    public void cargarRadioPregunta20() {
        ButtonGroup grupoPregunta20 = new ButtonGroup();
        grupoPregunta20.add(radioNuncaPregunta23);
        grupoPregunta20.add(radioVecesPregunta23);
        grupoPregunta20.add(radioSiemprePregunta23);

    }

    public void cargarRadioPregunta21() {
        ButtonGroup grupoPregunta21 = new ButtonGroup();
        grupoPregunta21.add(radioNuncaPregunta24);
        grupoPregunta21.add(radioVecesPregunta24);
        grupoPregunta21.add(radioSiemprePregunta24);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelPregunta8 = new javax.swing.JLabel();
        btnSiguiente8 = new javax.swing.JButton();
        panelPregunta24 = new javax.swing.JPanel();
        labelPregunta24 = new javax.swing.JLabel();
        radioNuncaPregunta24 = new javax.swing.JRadioButton();
        radioVecesPregunta24 = new javax.swing.JRadioButton();
        radioSiemprePregunta24 = new javax.swing.JRadioButton();
        panelPregunta23 = new javax.swing.JPanel();
        labelPregunta23 = new javax.swing.JLabel();
        radioNuncaPregunta23 = new javax.swing.JRadioButton();
        radioVecesPregunta23 = new javax.swing.JRadioButton();
        radioSiemprePregunta23 = new javax.swing.JRadioButton();
        panelPregunta22 = new javax.swing.JPanel();
        labelPregunta22 = new javax.swing.JLabel();
        radioNuncaPregunta22 = new javax.swing.JRadioButton();
        radioVecesPregunta22 = new javax.swing.JRadioButton();
        radioSiemprePregunta22 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelPregunta8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPregunta8.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelPregunta8, gridBagConstraints);

        btnSiguiente8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente8.setText("Siguiente");
        btnSiguiente8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSiguiente8, gridBagConstraints);

        panelPregunta24.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta24.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta24.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta24.setText("24. Mantengo conversaciones con la gente.");
        panelPregunta24.add(labelPregunta24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta24.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta24.setText("Nunca");
        radioNuncaPregunta24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta24ActionPerformed(evt);
            }
        });
        panelPregunta24.add(radioNuncaPregunta24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta24.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta24.setText("Algunas veces");
        radioVecesPregunta24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta24ActionPerformed(evt);
            }
        });
        panelPregunta24.add(radioVecesPregunta24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta24.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta24.setText("Siempre");
        radioSiemprePregunta24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta24ActionPerformed(evt);
            }
        });
        panelPregunta24.add(radioSiemprePregunta24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta24, gridBagConstraints);

        panelPregunta23.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta23.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta23.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta23.setText("23. Comprendo los sentimientos de los demás.");
        panelPregunta23.add(labelPregunta23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta23.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta23.setText("Nunca");
        radioNuncaPregunta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta23ActionPerformed(evt);
            }
        });
        panelPregunta23.add(radioNuncaPregunta23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta23.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta23.setText("Algunas veces");
        radioVecesPregunta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta23ActionPerformed(evt);
            }
        });
        panelPregunta23.add(radioVecesPregunta23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta23.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta23.setText("Siempre");
        radioSiemprePregunta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta23ActionPerformed(evt);
            }
        });
        panelPregunta23.add(radioSiemprePregunta23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta23, gridBagConstraints);

        panelPregunta22.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta22.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta22.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta22.setText("22. Soy una persona activa, me gusta hacer cosas.");
        panelPregunta22.add(labelPregunta22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta22.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta22.setText("Nunca");
        radioNuncaPregunta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta22ActionPerformed(evt);
            }
        });
        panelPregunta22.add(radioNuncaPregunta22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta22.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta22.setText("Algunas veces");
        radioVecesPregunta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta22ActionPerformed(evt);
            }
        });
        panelPregunta22.add(radioVecesPregunta22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta22.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta22.setText("Siempre");
        radioSiemprePregunta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta22ActionPerformed(evt);
            }
        });
        panelPregunta22.add(radioSiemprePregunta22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta22, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente8ActionPerformed
         if(!validar.preguntaUno || !validar.preguntaDos || !validar.preguntaTres ){
             JOptionPane.showMessageDialog(null, "Por favor, seleccione todas las preguntas");
        
        
        }
        else {
         cuestionarioOcho.retornarSubtotal();
        cuestionarioOcho.retornarTotal();
        
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioOcho.retornarSubtotal() );
//        JOptionPane.showMessageDialog(null, "El subtotal es "+cuestionarioOcho.retornarTotal() );
        VentanaPreguntas9 ventanaNueve = new VentanaPreguntas9(cuestionarioOcho.retornarTotal());
        ventanaNueve.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnSiguiente8ActionPerformed

    private void radioNuncaPregunta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta22ActionPerformed
       if(radioNuncaPregunta22.isSelected() == true){
           cuestionarioOcho.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
           validar.preguntaUno = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 1 es " + cuestionarioOcho.getValorPreguntaUno());
       
       }
    }//GEN-LAST:event_radioNuncaPregunta22ActionPerformed

    private void radioVecesPregunta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta22ActionPerformed
          if(radioVecesPregunta22.isSelected() == true){
           cuestionarioOcho.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
           validar.preguntaUno = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 1 es " + cuestionarioOcho.getValorPreguntaUno());
       
       }
    }//GEN-LAST:event_radioVecesPregunta22ActionPerformed

    private void radioSiemprePregunta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta22ActionPerformed
          if(radioSiemprePregunta22.isSelected() == true){
           cuestionarioOcho.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
           validar.preguntaUno = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 1 es " + cuestionarioOcho.getValorPreguntaUno());
       
       }
    }//GEN-LAST:event_radioSiemprePregunta22ActionPerformed

    private void radioNuncaPregunta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta23ActionPerformed
        if(radioNuncaPregunta23.isSelected() == true){
            cuestionarioOcho.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta 2 es " + cuestionarioOcho.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioNuncaPregunta23ActionPerformed

    private void radioVecesPregunta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta23ActionPerformed
         if(radioVecesPregunta23.isSelected() == true){
            cuestionarioOcho.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta 2 es " + cuestionarioOcho.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioVecesPregunta23ActionPerformed

    private void radioSiemprePregunta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta23ActionPerformed
         if(radioSiemprePregunta23.isSelected() == true){
            cuestionarioOcho.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor de la pregunta 2 es " + cuestionarioOcho.getValorPreguntaDos());
        
        }
    }//GEN-LAST:event_radioSiemprePregunta23ActionPerformed

    private void radioNuncaPregunta24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta24ActionPerformed
       if(radioNuncaPregunta24.isSelected()){
           cuestionarioOcho.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 3 es "+ cuestionarioOcho.getValorPreguntaTres());
       }
    }//GEN-LAST:event_radioNuncaPregunta24ActionPerformed

    private void radioVecesPregunta24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta24ActionPerformed
        if(radioVecesPregunta24.isSelected()){
           cuestionarioOcho.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 3 es "+ cuestionarioOcho.getValorPreguntaTres());
       }
    }//GEN-LAST:event_radioVecesPregunta24ActionPerformed

    private void radioSiemprePregunta24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta24ActionPerformed
         if(radioSiemprePregunta24.isSelected()){
           cuestionarioOcho.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
           validar.preguntaTres = true;
           //JOptionPane.showMessageDialog(null, "El valor de la pregunta 3 es "+ cuestionarioOcho.getValorPreguntaTres());
       }
    }//GEN-LAST:event_radioSiemprePregunta24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta22;
    private javax.swing.JLabel labelPregunta23;
    private javax.swing.JLabel labelPregunta24;
    private javax.swing.JLabel labelPregunta8;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta22;
    private javax.swing.JPanel panelPregunta23;
    private javax.swing.JPanel panelPregunta24;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta22;
    private javax.swing.JRadioButton radioNuncaPregunta23;
    private javax.swing.JRadioButton radioNuncaPregunta24;
    private javax.swing.JRadioButton radioSiemprePregunta22;
    private javax.swing.JRadioButton radioSiemprePregunta23;
    private javax.swing.JRadioButton radioSiemprePregunta24;
    private javax.swing.JRadioButton radioVecesPregunta22;
    private javax.swing.JRadioButton radioVecesPregunta23;
    private javax.swing.JRadioButton radioVecesPregunta24;
    // End of variables declaration//GEN-END:variables
}
