/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

import Clases.Cuestionario;
import Clases.Validacion;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class VentanaPreguntas3 extends javax.swing.JFrame  {

    public int valorPasado;
    Cuestionario cuestionarioTres;
    Validacion validar;
   

    public VentanaPreguntas3() {
        initComponents();
        this.setLocationRelativeTo(this);
        cargarRadioBotones();

    }

    public VentanaPreguntas3(int valorPasado) {
       
        this.valorPasado = valorPasado;
        initComponents();
        this.setLocationRelativeTo(this);
        
        cargarRadioBotones();
        cargarClases(this.valorPasado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/test.png")));
        

    }

    public void cargarRadioBotones() {
        cargarRadioPreguntaSiete();
        cargarRadioPreguntaOcho();
        cargarRadioPreguntaNueve();

    }

   

    public void cargarClases(int valorPasado) {
        cuestionarioTres = new Cuestionario(valorPasado);
        validar = new Validacion();

    }

    public void cargarRadioPreguntaSiete() {
        ButtonGroup grupoPreguntaSiete = new ButtonGroup();
        grupoPreguntaSiete.add(radioNuncaPregunta7);
        grupoPreguntaSiete.add(radioVecesPregunta7);
        grupoPreguntaSiete.add(radioSiemprePregunta7);

    }

    public void cargarRadioPreguntaOcho() {
        ButtonGroup grupoPreguntaOcho = new ButtonGroup();
        grupoPreguntaOcho.add(radioNuncaPregunta8);
        grupoPreguntaOcho.add(radioVecesPregunta8);
        grupoPreguntaOcho.add(radioSiemprePregunta8);

    }

    public void cargarRadioPreguntaNueve() {
        ButtonGroup grupoPreguntaNueve = new ButtonGroup();
        grupoPreguntaNueve.add(radioNuncaPregunta9);
        grupoPreguntaNueve.add(radioVecesPregunta9);
        grupoPreguntaNueve.add(radioSiemprePregunta9);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        labelTItulo3 = new javax.swing.JLabel();
        btnSiguiente3 = new javax.swing.JButton();
        panelPregunta9 = new javax.swing.JPanel();
        labelPregunta9 = new javax.swing.JLabel();
        radioNuncaPregunta9 = new javax.swing.JRadioButton();
        radioVecesPregunta9 = new javax.swing.JRadioButton();
        radioSiemprePregunta9 = new javax.swing.JRadioButton();
        panelPregunta8 = new javax.swing.JPanel();
        labelPreguntra8 = new javax.swing.JLabel();
        radioNuncaPregunta8 = new javax.swing.JRadioButton();
        radioVecesPregunta8 = new javax.swing.JRadioButton();
        radioSiemprePregunta8 = new javax.swing.JRadioButton();
        panelPregunta7 = new javax.swing.JPanel();
        labelPregunta7 = new javax.swing.JLabel();
        radioNuncaPregunta7 = new javax.swing.JRadioButton();
        radioVecesPregunta7 = new javax.swing.JRadioButton();
        radioSiemprePregunta7 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(1400, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelLateral.setBackground(new java.awt.Color(162, 179, 139));

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLateral, gridBagConstraints);

        panelDerecho.setBackground(new java.awt.Color(228, 233, 190));
        panelDerecho.setLayout(new java.awt.GridBagLayout());

        labelTItulo3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTItulo3.setText("PREGUNTAS DEL TEST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(labelTItulo3, gridBagConstraints);

        btnSiguiente3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSiguiente3.setText("Siguiente");
        btnSiguiente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 40;
        panelDerecho.add(btnSiguiente3, gridBagConstraints);

        panelPregunta9.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta9.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta9.setText("9. Mi fijo en el lado positivo de las cosas, soy optimista. ");
        panelPregunta9.add(labelPregunta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta9.setText("Nunca");
        radioNuncaPregunta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta9ActionPerformed(evt);
            }
        });
        panelPregunta9.add(radioNuncaPregunta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta9.setText("Algunas veces");
        radioVecesPregunta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta9ActionPerformed(evt);
            }
        });
        panelPregunta9.add(radioVecesPregunta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta9.setText("Siempre");
        radioSiemprePregunta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta9ActionPerformed(evt);
            }
        });
        panelPregunta9.add(radioSiemprePregunta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta9, gridBagConstraints);

        panelPregunta8.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta8.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPreguntra8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPreguntra8.setText("8. Cuando los demás me provocan intencionadamente soy capaz de no responder. ");
        panelPregunta8.add(labelPreguntra8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta8.setText("Nunca");
        radioNuncaPregunta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta8ActionPerformed(evt);
            }
        });
        panelPregunta8.add(radioNuncaPregunta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta8.setText("Algunas veces");
        radioVecesPregunta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta8ActionPerformed(evt);
            }
        });
        panelPregunta8.add(radioVecesPregunta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta8.setText("Siempre");
        radioSiemprePregunta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta8ActionPerformed(evt);
            }
        });
        panelPregunta8.add(radioSiemprePregunta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta8, gridBagConstraints);

        panelPregunta7.setBackground(new java.awt.Color(250, 253, 214));
        panelPregunta7.setPreferredSize(new java.awt.Dimension(625, 170));
        panelPregunta7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPregunta7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        labelPregunta7.setText("7. Cuando hago las cosas bien me felicito a mí mismo. ");
        panelPregunta7.add(labelPregunta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, -1));

        radioNuncaPregunta7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioNuncaPregunta7.setText("Nunca");
        radioNuncaPregunta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNuncaPregunta7ActionPerformed(evt);
            }
        });
        panelPregunta7.add(radioNuncaPregunta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        radioVecesPregunta7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioVecesPregunta7.setText("Algunas veces");
        radioVecesPregunta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVecesPregunta7ActionPerformed(evt);
            }
        });
        panelPregunta7.add(radioVecesPregunta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioSiemprePregunta7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        radioSiemprePregunta7.setText("Siempre");
        radioSiemprePregunta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSiemprePregunta7ActionPerformed(evt);
            }
        });
        panelPregunta7.add(radioSiemprePregunta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelDerecho.add(panelPregunta7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelPrincipal.add(panelDerecho, gridBagConstraints);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente3ActionPerformed
        if (!validar.preguntaUno || !validar.preguntaDos || !validar.preguntaTres) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione todas la preguntas");

        } else {
            cuestionarioTres.retornarSubtotal();
            cuestionarioTres.retornarTotal();

//            JOptionPane.showMessageDialog(null, "El valor total es " + cuestionarioTres.retornarTotal());
            
            VentanaPreguntas4 ventanaCuatro = new VentanaPreguntas4(cuestionarioTres.retornarTotal());
            ventanaCuatro.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnSiguiente3ActionPerformed

    private void radioVecesPregunta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta7ActionPerformed
        if (radioVecesPregunta7.isSelected() == true) {
            cuestionarioTres.setValorPreguntaUno(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaUno = true;
            // JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaUno());

        }
    }//GEN-LAST:event_radioVecesPregunta7ActionPerformed

    private void radioNuncaPregunta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta7ActionPerformed
        if (radioNuncaPregunta7.isSelected() == true) {
            cuestionarioTres.setValorPreguntaUno(new Cuestionario().asignarValorNunca());
            validar.preguntaUno = true;
            //JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaUno());

        }
    }//GEN-LAST:event_radioNuncaPregunta7ActionPerformed

    private void radioSiemprePregunta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta7ActionPerformed
        if (radioSiemprePregunta7.isSelected() == true) {
            cuestionarioTres.setValorPreguntaUno(new Cuestionario().asignarValorSiempre());
            validar.preguntaUno = true;
            // JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaUno());

        }
    }//GEN-LAST:event_radioSiemprePregunta7ActionPerformed

    private void radioNuncaPregunta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta8ActionPerformed
        if (radioNuncaPregunta8.isSelected() == true) {
            cuestionarioTres.setValorPreguntaDos(new Cuestionario().asignarValorNunca());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaDos());

        }
    }//GEN-LAST:event_radioNuncaPregunta8ActionPerformed

    private void radioVecesPregunta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta8ActionPerformed
        if (radioVecesPregunta8.isSelected() == true) {
            cuestionarioTres.setValorPreguntaDos(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaDos());

        }
    }//GEN-LAST:event_radioVecesPregunta8ActionPerformed

    private void radioSiemprePregunta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta8ActionPerformed
        if (radioSiemprePregunta8.isSelected() == true) {
            cuestionarioTres.setValorPreguntaDos(new Cuestionario().asignarValorSiempre());
            validar.preguntaDos = true;
            //JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaDos());

        }
    }//GEN-LAST:event_radioSiemprePregunta8ActionPerformed

    private void radioNuncaPregunta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNuncaPregunta9ActionPerformed
        if (radioNuncaPregunta9.isSelected() == true) {
            cuestionarioTres.setValorPreguntaTres(new Cuestionario().asignarValorNunca());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaTres());

        }

    }//GEN-LAST:event_radioNuncaPregunta9ActionPerformed

    private void radioVecesPregunta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVecesPregunta9ActionPerformed
        if (radioVecesPregunta9.isSelected() == true) {
            cuestionarioTres.setValorPreguntaTres(new Cuestionario().asignarValorAlgunasVeces());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaTres());

        }
    }//GEN-LAST:event_radioVecesPregunta9ActionPerformed

    private void radioSiemprePregunta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSiemprePregunta9ActionPerformed
        if (radioSiemprePregunta9.isSelected() == true) {
            cuestionarioTres.setValorPreguntaTres(new Cuestionario().asignarValorSiempre());
            validar.preguntaTres = true;
            //JOptionPane.showMessageDialog(null, "El valor para asignar a 1p es " + cuestionarioTres.getValorPreguntaTres());

        }
    }//GEN-LAST:event_radioSiemprePregunta9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreguntas3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreguntas3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPregunta7;
    private javax.swing.JLabel labelPregunta9;
    private javax.swing.JLabel labelPreguntra8;
    private javax.swing.JLabel labelTItulo3;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPregunta7;
    private javax.swing.JPanel panelPregunta8;
    private javax.swing.JPanel panelPregunta9;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioNuncaPregunta7;
    private javax.swing.JRadioButton radioNuncaPregunta8;
    private javax.swing.JRadioButton radioNuncaPregunta9;
    private javax.swing.JRadioButton radioSiemprePregunta7;
    private javax.swing.JRadioButton radioSiemprePregunta8;
    private javax.swing.JRadioButton radioSiemprePregunta9;
    private javax.swing.JRadioButton radioVecesPregunta7;
    private javax.swing.JRadioButton radioVecesPregunta8;
    private javax.swing.JRadioButton radioVecesPregunta9;
    // End of variables declaration//GEN-END:variables

  
}
